### ISSUE TITLE
Apply LinkIt integration programmatically

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_page_components#13]
There is [appetite](https://github.com/localgovdrupal/localgov_page_components/pull/6#issuecomment-829340921) for activating the LinkIt integration as soon as this module is available.  At the moment this is an optional and manual process [described in the README](https://github.com/localgovdrupal/localgov_page_components/blob/master/README.md#linkit-integration).

This will most like involve implementing [hook_install()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_install/9.1.x) or one of [its cousins](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_modules_installed/9.1.x). There's some [sample code in a test file](https://github.com/localgovdrupal/localgov_page_components/blob/b14286d5974d9e9d72b8c095488d8cfd78956c2a/tests/src/Kernel/LinkItIntegrationTest.php#L37).

**Comment by mattrfletcher** [comment]
Hi @Adnan-cds I'm currently looking at this. 

Is Linkit going to be added as a dependency for page components.

**Comment by mattrfletcher** [comment]
I've now finished working on this for now. I've submitted a pull request #18

Just to check this fix wont work if Linkit isn't enabled but am I right in thinking that this is enabled by default. 

cc @Adnan-cds @finnlewis

**Comment by Adnan-cds** [comment]
> Is Linkit going to be added as a dependency for page components.

Hi Matt, many thanks for looking into this.  The idea is, if LinkIt is available, the integration will be programmatically configured.  If not, nothing will be done.

> I've now finished working on this for now. I've submitted a pull request #18

Thanks for the pull request.  I will add some feedback in a few days.  Sorry for not being quicker.

**Comment by mattrfletcher** [comment]
@Adnan-cds Thanks for Clarifying. Will check with a colleague that i worked on it with and see if this is good. 

i'm fine with it taking a few days wasn't sure if it was a good time to submit changes with the version tagging and upgrading to Drupal 9 but thanks for looking at it.
