### ISSUE TITLE
Can't add new Contact Page component

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_page_components#22]
## How to reproduce
- Open /admin/content/paragraphs/add/default
- Select "Add Contact" from the only dropdown in the page.
- Nothing happens.  A Contact Paragraph creation form should have appeared.
- Ajax error message appear in the browser's Javascript console.
- PHP exception logged in Drupal's log: ```TypeError: Argument 1  passed to Drupal\Core\Render\Element::children() must be of the type  array, null given, called in  /path/to/localgov-project/web/core/themes/claro/src/ClaroPreRender.php  on line 87 in Drupal\Core\Render\Element::children() (line 71 of /path/to/localgov-project/web/core/lib/Drupal/Core/Render/Element.php)```
- All works fine if I switch to the "Seven" admin theme.

Needs some digging in to find out what's happening inside the Gin/Claro themes.

@finnlewis @MattOz-CDS @stephen-cox @danchamp

**Comment by danchamp** [comment]
@Adnan-cds We came across this in Cumbria, it's a known issue for paragraph types with vertical tabs in Claro:

https://www.drupal.org/project/drupal/issues/3223319

Changing tabs to horizontal for the Contact paragraph type fixed it for us, I haven't tried the recent patch in the Drupal project issue.

**Comment by danchamp** [comment]
Sorry, I thought I'd raised issues for everything like this we came across, but this one slipped through the net.

**Comment by Adnan-cds** [comment]
Thanks Dan.  Good to know it's a core bug.

**Comment by Adnan-cds** [comment]
The [patch](https://www.drupal.org/project/drupal/issues/3223319) attached to the d.o ticket is outdated.  A little tweak makes it usable, but I am unsure if the logic in the patch is fully reliable given there has not been much discussion around it yet.  Telling the Contact Paragraph to use a Horizon tab in its form display works as you have said, but then its form looks odd.  I am wondering what to do. @danchamp

**Comment by Adnan-cds** [comment]
No longer an issue following a [core fix](https://www.drupal.org/project/drupal/issues/3223319).
