### ISSUE TITLE
Update field_page_components to localgov_page_components

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_page_components#8]
Related to:
- localgovdrupal/localgov#112
- localgovdrupal/localgov_core#37
- localgovdrupal/localgov_services#91

Rename the field_storage and add the update.
Followup will need to be made in localgov_services to support the field.

**Comment by Adnan-cds** [comment]
This is done, right? @andybroomfield

**Comment by andybroomfield** [comment]
I believe so @Adnan-cds

**Comment by Adnan-cds** [comment]
Thanks for the confirmation Andy.  Closing...
